// <auto-generated />
using System;
using FlightsAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FlightsAPI.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FlightsAPI.Models.Flight", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<Guid>("number")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Flights");
                });

            modelBuilder.Entity("FlightsAPI.Models.Leg", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CrossingTime")
                        .HasColumnType("int");

                    b.Property<int?>("flightId")
                        .HasColumnType("int");

                    b.Property<int>("nextLegId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("flightId");

                    b.ToTable("Legs");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CrossingTime = 1000,
                            nextLegId = 2
                        },
                        new
                        {
                            Id = 2,
                            CrossingTime = 1000,
                            nextLegId = 3
                        },
                        new
                        {
                            Id = 3,
                            CrossingTime = 2000,
                            nextLegId = 4
                        },
                        new
                        {
                            Id = 4,
                            CrossingTime = 8000,
                            nextLegId = 5
                        },
                        new
                        {
                            Id = 5,
                            CrossingTime = 3000,
                            nextLegId = 6
                        },
                        new
                        {
                            Id = 6,
                            CrossingTime = 5000,
                            nextLegId = 7
                        },
                        new
                        {
                            Id = 7,
                            CrossingTime = 5000,
                            nextLegId = 8
                        },
                        new
                        {
                            Id = 8,
                            CrossingTime = 2000,
                            nextLegId = 4
                        });
                });

            modelBuilder.Entity("FlightsAPI.Models.Log", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("FlightId")
                        .HasColumnType("int");

                    b.Property<DateTime>("In")
                        .HasColumnType("datetime2");

                    b.Property<int>("LegId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("Out")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Logs");
                });

            modelBuilder.Entity("FlightsAPI.Models.Leg", b =>
                {
                    b.HasOne("FlightsAPI.Models.Flight", "flight")
                        .WithMany()
                        .HasForeignKey("flightId");

                    b.Navigation("flight");
                });
#pragma warning restore 612, 618
        }
    }
}
